# -------------------------
# Image
# -------------------------
image:
  repository: myacrtask.azurecr.io/chatbot-app
  tag: latest
  pullPolicy: Always

# -------------------------
# App settings
# -------------------------
app:
  name: chatbot-service
  replicas: 2
  env:
    AOAI_ENDPOINT: ""          # injected from Key Vault or GitHub Secret
    AOAI_DEPLOYMENT: ""        # "
    AOAI_API_KEY: ""           # "
    USE_REDIS: "true"
    REDIS_URL: "rediss://chatbot-redis-2025:6380"
    USE_COSMOS: "true"
    COSMOS_FILE: "/data/cosmos_mock.json"   # only fallback; real cosmos wired later

# -------------------------
# Service
# -------------------------
service:
  type: ClusterIP
  port: 8080

# -------------------------
# Ingress (App Gateway Ingress Controller)
# -------------------------
ingress:
  enabled: true
  className: azure-application-gateway
  annotations:
    # Remove the kubernetes.io/ingress.class line - it conflicts with className
    # REQUIRED: Backend protocol
    appgw.ingress.kubernetes.io/backend-protocol: http
    # Use private frontend for internal APIM access
    appgw.ingress.kubernetes.io/frontend-ip: appgw-feip-private
    # Request timeout
    appgw.ingress.kubernetes.io/request-timeout: "30"
  hosts:
    - host: chatbot.kpmg.local
      paths:
        - path: /
          pathType: Prefix
        - path: /chat
          pathType: Prefix
  tls: []   # leave empty → AGIC can handle cert if we bring one later

# -------------------------
# Resources
# -------------------------
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# -------------------------
# Liveness / Readiness
# -------------------------
livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10