name: Destroy Chatbot Infra + App

on:
  workflow_dispatch:   # ✅ manual trigger only

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: infra
      RESOURCE_GROUP: platform_candidate_2
      CLUSTER_NAME: chatbot-aks
      REGION: eastus2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal with Secret)
        uses: azure/login@v2
        with:
          auth-type: SERVICE_PRINCIPAL
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Cleanup AKS-related workloads (not strictly required, but safe)
      - name: Get AKS Credentials
        run: az aks get-credentials -g $RESOURCE_GROUP -n $CLUSTER_NAME --overwrite-existing
        continue-on-error: true

      - name: Uninstall Helm Releases
        run: |
          helm uninstall chatbot -n chatbot || true
          helm uninstall agic -n kube-system || true
        continue-on-error: true

      - name: Scale down node pool
        run: |
          az aks nodepool scale \
            --cluster-name $CLUSTER_NAME \
            --resource-group $RESOURCE_GROUP \
            --name systempool \
            --node-count 0 || true
        continue-on-error: true

      # Terraform destroy (APIM + networking first)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Destroy (APIM reset)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform destroy -auto-approve \
            -target=azurerm_api_management.chatbot_apim \
            -target=azurerm_api_management_api.chatbot_api \
            -target=azurerm_api_management_api_policy.rate_limit_policy \
            -target=azurerm_subnet.apim_subnet \
            -target=azurerm_subnet_network_security_group_association.apim_assoc \
            -target=azurerm_network_security_group.apim_nsg \
            -target=azurerm_route_table.apim_rt \
            -target=azurerm_subnet_route_table_association.apim_subnet_rt
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
