name: Destroy Chatbot Infra + App

on:
  workflow_dispatch:   # ✅ manual trigger only

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: infra
      RESOURCE_GROUP: platform_candidate_2
      CLUSTER_NAME: chatbot-aks
      REGION: eastus2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 🧹 Cleanup AKS-related workloads (safe cleanup, doesn't block destroy)
      - name: Get AKS Credentials
        run: az aks get-credentials -g $RESOURCE_GROUP -n $CLUSTER_NAME --overwrite-existing
        continue-on-error: true

      - name: Uninstall Helm Releases
        run: |
          helm uninstall chatbot -n chatbot || true
          helm uninstall agic -n kube-system || true
        continue-on-error: true

      - name: Scale down node pool
        run: |
          az aks nodepool scale \
            --cluster-name $CLUSTER_NAME \
            --resource-group $RESOURCE_GROUP \
            --name systempool \
            --node-count 0 || true
        continue-on-error: true

      # 💣 Terraform destroy
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
          ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}

      - name: Terraform Destroy (full infra)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve
        env:
          ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
          ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
